### ISSUE TITLE
DEFRA-Greenhouse-gas-emissions-UK-consumption

### ISSUE THREAD

**Issue by osamede20** [GSS-Cogs/family-climate-change#513]
- [x] Transform specified
- [x] Transform implemented
- [x] Codelists created
- [x] Column mapping
- [x] Additional metadata
- [x] Reviewed
- [x] Periodic build trigger

**Comment by Shannon95** [comment]
This Dataset transform is complete. 

Published to both pmd staging and beta: 
Staging: [Greenhouse gas emissions UK consumption](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fclimate-change%2Fdefra-greenhouse-gas-emissions-uk-consumption%2Fgreenhouse-gas-emissions-uk-consumption%23dataset-catalog-entry)
Beta: Greenhouse gas emissions UK consumption

Pending on pmd Beta atm, once complete I will attach link to above.
