### ISSUE TITLE
beta pipelines

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-climate-change#59]
Set up Jenkins pipelines to load to beta.gss-data.org.uk

- [x] Adjust `datasets/info.json` with Jenkins job path and run `repo-sync -j`
- [x] Copy in `shared` pipeline for family level reference data.
- [x] Run builds and check outputs.
- [x] Sort out issue with ref_periods, GSS-Cogs/pmd-jenkins-library#71.

**Comment by JasonHowell** [comment]
@Shannon95  @osamede20 have all pipelines now run and can this card be closed?

**Comment by Shannon95** [comment]
Yes I believe this can now be closed.

**Comment by JasonHowell** [comment]
As per comments above.  Closed.
