### ISSUE TITLE
BEIS-Final-UK-greenhouse-gas-emissions-national-statistics

### ISSUE THREAD

**Issue by Shannon95** [GSS-Cogs/family-climate-change#9]
- [ ] Transform specified
- [ ] Transform implemented
- [ ] Codelists created
- [ ] Column mapping
- [ ] Additional metadata
- [ ] Reviewed
- [ ] Periodic build trigger

**Comment by AndrewtGSScogs** [comment]
This Dataset is on PMD so we will QA it with BEIS ASAP
